### ISSUE TITLE
static error with QP control when trying to stand still

### ISSUE THREAD

**Issue by chalkchalk** [ShuoYangRobotics/A1-QP-MPC-Controller#14]
I'm trying to use the code of QP control to let the robot stand up and stay still. However, no matter how I tune the parameter of the controoller or the robot model, the robot still cannot achieve the desired attitude within acceptable error, especially the body height and roll angle. 
My question is, how does the QP controller deal with such static error, when there is no integral term in the control loop? Besides, how is the performance of QP control in your hardware implementation? Can the robot stand level and still?

**Comment by chalkchalk** [comment]
Problem solved by better parameter tuning.

**Comment by Sora-dw** [comment]
> Problem solved by better parameter tuning.

Could you please share your parameter tuning process or concrete parameters? I met the same question as yours, thank you! If you'd like, my email is wding_01@stu.xidian.edu.cn.
