### ISSUE TITLE
ERR when execute    docker build -t a1_cpp_ctrl_image .

### ISSUE THREAD

**Issue by dbdxnuliba** [ShuoYangRobotics/A1-QP-MPC-Controller#2]
Step 56/81 : RUN git clone https://github.com/unitreerobotics/aliengo_sdk.git &&     cd ${SUPPORT_WS}/aliengo_sdk &&     mkdir build &&     cd build &&     cmake .. &&     make -j12
 ---> Using cache
 ---> 7f0dc61c9f78
Step 57/81 : RUN   if [ "x$(nproc)" = "x1" ] ; then export USE_PROC=1 ;       else export USE_PROC=$(($(nproc)/2)) ; fi &&       apt-get update && apt-get install -y       ros-${ROS_DISTRO}-ros-control       ros-${ROS_DISTRO}-gazebo-ros       ros-${ROS_DISTRO}-joy       ros-${ROS_DISTRO}-ros-controllers       ros-${ROS_DISTRO}-robot-state-publisher
 ---> Running in 20366730b24e
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Connection failed [IP: 91.189.91.38 80]
Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
  Connection failed [IP: 91.189.91.38 80]
Hit:3 http://packages.ros.org/ros/ubuntu bionic InRelease
Err:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Connection failed [IP: 91.189.91.39 80]
Err:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Connection failed [IP: 91.189.91.38 80]
Reading package lists...
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-latest.list:1 and /etc/apt/sources.list.d/ros1-latest.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-latest.list:1 and /etc/apt/sources.list.d/ros1-latest.list:1
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Connection failed [IP: 91.189.91.38 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Connection failed [IP: 91.189.91.39 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Connection failed [IP: 91.189.91.38 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Connection failed [IP: 91.189.91.38 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-latest.list:1 and /etc/apt/sources.list.d/ros1-latest.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-latest.list:1 and /etc/apt/sources.list.d/ros1-latest.list:1
Reading package lists...
Building dependency tree...

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.58.0-2ubuntu3.17_amd64.deb  Connection failed [IP: 91.189.91.38 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-lato/fonts-lato_2.0-2_all.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/q/qtsvg-opensource-src/libqt5svg5_5.9.5-0ubuntu1.1_amd64.deb  Connection failed [IP: 91.189.91.38 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libc/libccd/libccd2_2.0-1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/apparmor/libapparmor1_2.12-4ubuntu5.1_amd64.deb  Connection failed [IP: 91.189.91.38 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/fribidi/libfribidi0_0.19.7-2ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/slang2/libslang2_2.3.1a-3ubuntu1_amd64.deb  Connection failed [IP: 91.189.91.38 80]

**Comment by dbdxnuliba** [comment]
I‘'m trying    docker build -t a1_cpp_ctrl_image .  --no-cache

**Comment by dbdxnuliba** [comment]
but that cannot solve the problem,

**Comment by ShuoYangRobotics** [comment]
Please check your Internet connection. Make sure you can ping 91.189.91.38 80

**Comment by dbdxnuliba** [comment]
<pre><font color="#8AE234"><b>dell1804@dell1804-G3-3590</b></font>:<font color="#729FCF"><b>~</b></font>$ ping  91.189.91.38
PING 91.189.91.38 (91.189.91.38) 56(84) bytes of data.
64 bytes from 91.189.91.38: icmp_seq=1 ttl=51 time=222 ms
64 bytes from 91.189.91.38: icmp_seq=2 ttl=51 time=217 ms
64 bytes from 91.189.91.38: icmp_seq=3 ttl=51 time=223 ms
64 bytes from 91.189.91.38: icmp_seq=4 ttl=51 time=218 ms
64 bytes from 91.189.91.38: icmp_seq=5 ttl=51 time=218 ms
64 bytes from 91.189.91.38: icmp_seq=6 ttl=51 time=218 ms
64 bytes from 91.189.91.38: icmp_seq=7 ttl=51 time=219 ms
64 bytes from 91.189.91.38: icmp_seq=8 ttl=51 time=216 ms
64 bytes from 91.189.91.38: icmp_seq=9 ttl=51 time=217 ms
64 bytes from 91.189.91.38: icmp_seq=10 ttl=51 time=251 ms
64 bytes from 91.189.91.38: icmp_seq=11 ttl=51 time=217 ms
64 bytes from 91.189.91.38: icmp_seq=12 ttl=51 time=223 ms
64 bytes from 91.189.91.38: icmp_seq=13 ttl=51 time=217 ms
64 bytes from 91.189.91.38: icmp_seq=14 ttl=51 time=274 ms
^C
--- 91.189.91.38 ping statistics ---
14 packets transmitted, 14 received, 0% packet loss, time 13020ms
rtt min/avg/max/mdev = 216.676/225.562/274.959/16.174 ms
<font color="#8AE234"><b>dell1804@dell1804-G3-3590</b></font>:<font color="#729FCF"><b>~</b></font>$ 
</pre>

**Comment by dbdxnuliba** [comment]
but I have started succesfully in local machine without docker ,  I'm learning the program ,thanks

**Comment by zhangOSK** [comment]
Hi, I met a same problem when build -t a1_cpp_ctrl_image . . I can also ping 91.189.91.39 successfully. However, I failed to connect with IP: 91.189.91.39 80. Did you find the solution?
Here are the error reports:
Err:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-lato all 2.0-2
  Connection failed [IP: 91.189.91.39 80]
Err:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 freeglut3 amd64 2.8.1-3
  Connection failed [IP: 91.189.91.39 80]
Err:13 http://archive.ubuntu.com/ubuntu bionic/universe amd64 freeglut3-dev amd64 2.8.1-3
  Connection failed [IP: 91.189.91.39 80]
Err:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libasound2-data all 1.1.3-5ubuntu0.6
  Connection failed [IP: 91.189.91.39 80]
Err:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libasound2 amd64 1.1.3-5ubuntu0.6
  Connection failed [IP: 91.189.91.39 80]
Err:16 http://archive.ubuntu.com/ubuntu bionic/main amd64 libavc1394-0 amd64 0.5.4-4build1
  Connection failed [IP: 91.189.91.39 80]
Err:17 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libass9 amd64 1:0.14.0-1
  Connection failed [IP: 91.189.91.39 80]
Err:157 http://archive.ubuntu.com/ubuntu bionic/main amd64 libusb-1.0-doc all 2:1.0.21-2
  Connection failed [IP: 91.189.91.39 80]
Err:158 http://archive.ubuntu.com/ubuntu bionic/universe amd64 joystick amd64 1:1.6.0-2
  Connection failed [IP: 91.189.91.39 80]
Ign:159 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 unzip amd64 6.0-21ubuntu1.1
Err:160 http://archive.ubuntu.com/ubuntu bionic/main amd64 zip amd64 3.0-11build1
  Connection failed [IP: 91.189.91.39 80]
Get:156 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libsdl1.2debian amd64 1.2.15+dfsg2-0.1ubuntu0.2 [175 kB]
Err:161 http://archive.ubuntu.com/ubuntu bionic/universe amd64 evtest amd64 1:1.33-1build1
  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-lato/fonts-lato_2.0-2_all.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/freeglut/freeglut3_2.8.1-3_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/freeglut/freeglut3-dev_2.8.1-3_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/libasound2-data_1.1.3-5ubuntu0.6_all.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/libasound2_1.1.3-5ubuntu0.6_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/liba/libavc1394/libavc1394-0_0.5.4-4build1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/liba/libass/libass9_0.14.0-1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libu/libusb-1.0/libusb-1.0-doc_1.0.21-2_all.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/j/joystick/joystick_1.6.0-2_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/z/zip/zip_3.0-11build1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/e/evtest/evtest_1.33-1build1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c if [ "x$(nproc)" = "x1" ] ; then export USE_PROC=1 ;       else export USE_PROC=$(($(nproc)/2)) ; fi &&       apt-get update && apt-get install -y       ros-${ROS_DISTRO}-ros-control       ros-${ROS_DISTRO}-gazebo-ros       ros-${ROS_DISTRO}-joy       ros-${ROS_DISTRO}-ros-controllers       ros-${ROS_DISTRO}-robot-state-publisher' returned a non-zero code: 100

**Comment by zhangOSK** [comment]
It is internet connection problem. After building multiple times, the problem is solved without any modification.

**Comment by 1242713693** [comment]
你好，能浏览一下你运行代码的步骤吗？谢谢
