### ISSUE TITLE
Init-Compilation Failure Issue

### ISSUE THREAD

**Issue by mitsui29** [ShuoYangRobotics/A1-QP-MPC-Controller#29]
Hello, I recently started playing your code, but I encountered some issues during the initial compilation. In the following, it shows that the 'auxil.h' header file does not exist, and the error message is:

Errors << a1_cpp:make /root/A1_ctrl_ws/logs/a1_cpp/build.make.049.log
In file included from /usr/local/include/OsqpEigen/Solver.hpp:312:0,
from /usr/local/include/OsqpEigen/OsqpEigen.h:13,
from /root/A1_ctrl_ws/src/A1_Ctrl/A1-QP-MPC-Controller/src/a1_cpp/src/test/test_rotation.cpp:8:
/usr/local/include/OsqpEigen/Solver.tpp:10:10: fatal error: auxil.h: No such file or directory
#include <auxil.h>
^~~~~~~~~
![selection](https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller/assets/95944211/f81807e2-f309-40cf-babd-2d92fdfa0ad8)

I have tried some other methods（adding paths to the header files ; find the auxil.h path: /tmp/osqp/include/private and add to the include_directories in cmakelists） to resolve this issue, but each time I encounter similar errors indicating that other header files are missing or just completely wrong.  I also found that the auxil.h exits in some different path, which seems like a little bit strange here. I'm still relatively new to this, so I'm hoping to get your response. Thanks a lot!!

**Comment by mandelyoni** [comment]
Hi, I'm also having this problem.
Any ideas?
Thanks

**Comment by mitsui29** [comment]
Hey, delete the OSQP and OSQP-Eigen, try to download 0.6.3 osqp and 0.8.0 osqp-eigen. it will help u.

**Comment by mitsui29** [comment]
> Hi, I'm also having this problem. Any ideas? Thanks

Hey, delete the OSQP and OSQP-Eigen, try to download 0.6.3 osqp and 0.8.0 osqp-eigen. it will help u.
