### ISSUE TITLE
where is the wname and world file about the  picture.,thanks

### ISSUE THREAD

**Issue by dbdxnuliba** [ShuoYangRobotics/A1-QP-MPC-Controller#3]
![image](https://user-images.githubusercontent.com/13350158/166400486-a95a2927-ea81-44ac-9b16-7c3ade781ac9.png)
where is the wname and world file about the  picture.,thanks

**Comment by ShuoYangRobotics** [comment]
https://github.com/ShuoYangRobotics/unitree_ros/tree/master/unitree_gazebo/worlds

**Comment by yangcopnuli** [comment]
thanks
