### ISSUE TITLE
problem about trotting up stairs in gazebo 

### ISSUE THREAD

**Issue by zhuyijie88** [ShuoYangRobotics/A1-QP-MPC-Controller#4]
Hi, I tried your code in gazebo, running in the docker environment. The simulation step is small and the locomotion does not match with real-time performance. Also,  the parameters of ODE engine affect largely the locomotion. It seems that the dog never falls down from the stairs even when its head is in touch with the stairs, which is unreasonable in reality.

**Comment by ShuoYangRobotics** [comment]
Yes, all simulations are wrong. The simulation only helps you to be aware of what variables and behavior you should monitor when developing a hardware robot.
