### ISSUE TITLE
Misleading information for using joystick in docker

### ISSUE THREAD

**Issue by zhangOSK** [ShuoYangRobotics/A1-QP-MPC-Controller#8]
In the readme, 
"If there is a USB joystick connects to the host computer. The docker should be able to see it (because when we run the docker container, we use --device /dev/input to map USB input devices into the docker). So we can read its data in the docker. Open another terminal

ssh root@localhost -p2233
rosrun joy joy_node "

In my case, I cannot connect the joystick by running the command in docker. Instead, I run the command
rosrun joy joy_node
in the **host pc**, then the joystick can be found in the docker.

Someone else may encounter the same issue, it will be helpful if you can add some notes to remind them.

**Comment by ShuoYangRobotics** [comment]
Either way is correct. 

In your case your host computer has ROS1 installed. However other people who use Ubuntu 20.04 cannot install ROS1 on their host computers so they cannot run this command on host PC. 

But I agree your approach is easier for people who has host PC with ROS1 installed. 

Feel free to submit a pull request with more details. Thanks for your comments.
