### ISSUE TITLE
What is the parameter ‘km_foot’?

### ISSUE THREAD

**Issue by chalkchalk** [ShuoYangRobotics/A1-QP-MPC-Controller#9]
Find that the parameter _km_foot_ in code 
`Eigen::Vector3d force_tgt = state.km_foot.cwiseProduct(state.foot_forces_kin.block<3, 1>(0, i));`
Where 
`km_foot = Eigen::Vector3d(0.1, 0.1, 0.1);`
What does this parameter represent？Why not adjusting parameter _kp_foot_ and _kd_foot_ instead?

**Comment by ShuoYangRobotics** [comment]
Just another gain appears during swing leg controller derivation. I may add a document later to explain it. For now you can consider it as a scaling factor of target swing force
